### ISSUE TITLE
Pediatric MDR-TB data

### ISSUE THREAD

**Issue by mgro** [seabbs/getTBinR#62]
Hello Sam,

is there anyway to access data on MDR-TB stratified by age? I would be interested in visualizing MDR-TB cases only in children aged 0-14 years (as WHO routinely reports). 

Thank you! 

Best,
Matthias

**Comment by seabbs** [comment]
Checking the [WHO data source](https://www.who.int/tb/country/data/download/en/) it looks like they have done 1.

The minor added complexity here is that the data format has gone from wide (as for all other releases) to long (i.e tidy). This can easily be solved by either 1. converting to wide and joining or 2. adding as a separate data set. Unfortunately it does not look like a data dictionary has been produced at this time.

**Comment by seabbs** [comment]
Hi @mgro, 

In the new release, I have added all the datasets listed [here](https://www.who.int/tb/country/data/download/en/) excepting the WHO TB incidence estimates disaggregated by age and sex (which may be the dataset you wanted here)? 

Complexity for this one is the cleaning etc but I will look at including this in the next release (in about 2 months) 

Sorry for the delay! 

Sam

**Comment by seabbs** [comment]
Hi @mgro, 

Long delay on this and I think that you no longer need it - still useful to do!

In the latest release (on its way to CRAN now) I have added some experimental support for these data. Note it still requires quite a bit more manual manipulation than the other datasets. I expect the WHO team to update the formatting for this data at some point as the current implementation is quite crude in comparison to the other datasets. 

If the data format stays fixed I may be able to make things less clunky in later releases. 

Code example: 

```
library(getTBinR)
library(dplyr)

df <- get_tb_burden(additional_datasets = "Incidence by age and sex")

df_ag <- df %>% 
group_by(age_group, country, year) %>% 
summarise_at(.vars = vars(inc_age_sex, inc_age_sex_lo, inc_age_sex_hi), sum) %>%
full_join(select(tmp, -sex, -age_group, -contains("inc_age_sex")) %>% unique) %>% 
ungroup 

map_tb_burden(df_ag, metric = "inc_age_sex", metric_label = "Incidence by age",
              facet = c("age_group"), trans = "log10")
```

Closing for now - let me know if this is still something you would like to see more development on.
