### ISSUE TITLE
Incomplete LICENSE file

### ISSUE THREAD

**Issue by rrrlw** [seabbs/getTBinR#67]
GPL-3 is an appropriate OSI-approved license for a JOSS submission. However, the bottom of the LICENSE file in this repo is unfilled (note the use of angled brackets near the bottom, e.g. <name of author>, <year>).

Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/1260).

**Comment by seabbs** [comment]
Hi @rrrlw, 

Thanks for taking the time to review this. 

Could you give me the line numbers for the areas I need to change? 

Thanks!

**Comment by seabbs** [comment]
Looked at [here](https://github.com/tidyverse/dplyr/blob/master/LICENSE.md) as an example. 

Filled in the <> brackets with relevant details. 

Let me know if this needs changing etc.

**Comment by rrrlw** [comment]
The changes you made look good; maybe adding the word “Data” or similar to the end of line 634? All the areas I was looking at have been filled out.
